### PR TITLE
Add ukrainian locale

### PR DESCRIPTION
**Pull request by night-codes**

### CODE REVIEW

**Comment by prantlf** [comment]
Thanks a lot for your contribution! And also for fixing my Russian, which got much worse, since I left the elementary school :-) Your change has been published as dayjs-ext@1.0.2. (I need to fix the semantic versioning to get it 1.9.0.)

I do intend to push my changes to the original projects. However, the review process seems to take at least weeks there and I am in need of having an NPM module as soon as possible.

Just a small remark to your PR:

* Try committing your changes in a separate branch, which you branch off from `combined` by `git checkout -b ua-locale`, for example. It would be simpler to merge, if you continued with other changes, which you should prepare in other branches. On the other hand, a simple change like yours was no issue.
* If you know, that you're adding a new feature, you can prefix your commit message by `feat:`. For a bug fix by `fix:`. But it is no problem for me doing that before pushing you PM merged, as I did now.

Thanks again!

**Comment by prantlf** [comment]
Could you have a look at you personal e-mail, please? I have a difficulty to update the `dayjs-ext` package and I will need your help. Thank you!

**Comment by night-codes** [comment]
> Could you have a look at you personal e-mail, please? I have a difficulty to update the dayjs-ext package and I will need your help. Thank you!

Done! Sorry for my publication to NPM! I decided that the repository was abandoned, since the package mentioned in the documentation does not exist.

**Comment by prantlf** [comment]
Later I realized, that the Ukrainian localization was available as "uk". I compared it to your "ua" and found no differences. I'm removing it and merging you contribution to the "uk" locale, which is correct according to ISO 639. Let me know, if there is any problem with that. Thank you!

**Comment by night-codes** [comment]
It's ok, full language code is uk_UA so in different locales it can be "ua" or "uk"

**Pull request merged**
